name: Release
on:
  push:
    branches:
      - main

jobs:
  check-for-upgrade:
    name: Check for upgrade
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: check
        name: Check for package.json version upgrade
        uses: EndBug/version-check@v2.1.3
        with:
          diff-search: true
      - name: Log when changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version changed. New version: ${{ steps.check.outputs.version }}"'
      - name: Release
        if: steps.check.outputs.changed == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.check.outputs.version }}
      - name: Trigger release in main repo
        if: steps.check.outputs.changed == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: axherrm/WebCVTemplate
          event-type: release
          client-payload: '{"version": "v${{ steps.check.outputs.version }}"}'
